# Generated by Django 4.2.2 on 2025-04-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('loginId', models.CharField(max_length=50, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('status', models.CharField(default='waiting', max_length=20)),
            ],
        ),
    ]
